<?php
$data = array (
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => '进口水果',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '1',
    'goods_num' => '2',
    'level' => 0,
    'id' => '52',
    'name' => '进口水果',
  ),
  47 => 
  array (
    'cat_id' => '47',
    'cat_name' => '散装干果批发',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '47',
    'name' => '散装干果批发',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '国产水果',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '2',
    'goods_num' => '8',
    'level' => 0,
    'id' => '1',
    'name' => '国产水果',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => '珠光极品',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '55',
    'name' => '珠光极品',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => '珠光冰白',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '54',
    'name' => '珠光冰白',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => '精品礼盒',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '45',
    'name' => '精品礼盒',
  ),
  46 => 
  array (
    'cat_id' => '46',
    'cat_name' => '零食开心果',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '46',
    'name' => '零食开心果',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => '呜呜呜呜呜呜',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '57',
    'name' => '呜呜呜呜呜呜',
  ),
  56 => 
  array (
    'cat_id' => '56',
    'cat_name' => 'www',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '56',
    'name' => 'www',
  ),
);
?>